### PR TITLE
Fix test warning and update deps

### PR DESCRIPTION
**Pull request by seantanly**
The PR fixed a minor test warning, and upgraded hackney to the current version of `0.18.x` .

### CODE REVIEW

**Comment by seantanly** [comment]
@awolfden @sheldonvaughn @logangingerich

Is there anything that I can do to help get this merged sooner?

**Review by pliao28 — APPROVED** [review]

**Comment by pliao28** [comment]
@seantanly lgtm, merged!

**Comment by seantanly** [comment]
@pliao28 Thanks!

**Comment by seantanly** [comment]
@pliao28 noticed that there is a new version `0.1.3` of this library being built, however, it is not yet published/made available to hex.  ;)

**Pull request merged**
