### PR TITLE
Feature/sdk 136 move organizations out of portal and add

### PR DESCRIPTION
**Pull request by pliao28**

### CODE REVIEW

**Comment by juanazam** [comment]
Hello! Are there any updates on when this will get merged? Also it seems the code here is using the POST http verb for updating organizations and it should be PUT.

**Comment by juanazam** [comment]
@pliao28 Hello! do you have any updates regarding this PR? thanks!

**Comment by LauraBeatris** [comment]
Closing this PR for now since it's outdated, we're going to follow up with updates for the Portal module

**Comment by juanazam** [comment]
@LauraBeatris thanks for your reply, do you know when those updates are going to land?

**Comment by LauraBeatris** [comment]
@juanazam We are expecting to release a new version around the end of this week, with improvements to the current modules and refactoring of outdated functionalities based on the current API version

**Comment by juanazam** [comment]
Amazing!

**Comment by LauraBeatris** [comment]
Follow up https://github.com/workos/workos-elixir/pull/17

**Pull request closed without merging**
